#ifndef TOC_H
#define TOC_H

#define H5FILE "data.h5"

#define H5D_N_AO "/N/N_AO"      
#define H5D_N_MO "/N/N_MO"      
#define H5D_N_FRZ "/N/N_FRZ"    
#define H5D_N_COR "/N/N_COR"    
#define H5D_N_CAS_ORB "/N/N_CAS_ORB" 
#define H5D_N_CAS_ELE "/N/N_CAS_ELE"
#define H5D_N_OCC_ACT "/N/N_OCC_ACT" 
#define H5D_N_VIR_ACT "/N/N_VIR_ACT" 
#define H5D_N_MO_ACT "/N/N_MO_ACT" 
#define H5D_N_PTS "/N/N_PTS" 

#define H5D_C "/C"

#define H5D_H_CORE_AO "/H/H_CORE_AO"
#define H5D_H_CORE_MO "/H/H_CORE_MO"

#define H5D_E_NUC "/E/E_NUC"
#define H5D_E_CORE "/E/E_CORE"
#define H5D_E_HARTREE "/E/E_HARTREE"

#define H5D_JA_AO "/J/JA_AO"
#define H5D_JB_AO "/J/JB_AO"
#define H5D_JA_MO "/J/JA_MO"
#define H5D_JB_MO "/J/JB_MO"

#define H5D_FULL_D1A_MO "/D/D1/FULL_D1A_MO" 
#define H5D_FULL_D1B_MO "/D/D1/FULL_D1B_MO"
#define H5D_FULL_D1_MO  "/D/D1/FULL_D1_MO"

#define H5D_ACT_D1A_MO "/D/D1/ACT_D1A_MO"
#define H5D_ACT_D1B_MO "/D/D1/ACT_D1B_MO"
#define H5D_ACT_D1_MO "/D/D1/ACT_D1_MO"

#define H5D_SP_SYM_FULL_D1A_MO_NNZ "/SP_SYM_D1/FULL_D1a_MO/NNZ"
#define H5D_SP_SYM_FULL_D1A_MO_VAL "/SP_SYM_D1/FULL_D1a_MO/VAL"
#define H5D_SP_SYM_FULL_D1A_MO_ROW_IDX "/SP_SYM_D1/FULL_D1a_MO/ROW_IDX"
#define H5D_SP_SYM_FULL_D1A_MO_COL_IDX "/SP_SYM_D1/FULL_D1a_MO/COL_IDX"

#define H5D_SP_SYM_FULL_D1B_MO_NNZ "/SP_SYM_D1/FULL_D1b_MO/NNZ"
#define H5D_SP_SYM_FULL_D1B_MO_VAL "/SP_SYM_D1/FULL_D1b_MO/VAL"
#define H5D_SP_SYM_FULL_D1B_MO_ROW_IDX "/SP_SYM_D1/FULL_D1b_MO/ROW_IDX"
#define H5D_SP_SYM_FULL_D1B_MO_COL_IDX "/SP_SYM_D1/FULL_D1b_MO/COL_IDX"

#define H5D_SP_SYM_ACT_D1A_MO_NNZ "/SP_SYM_D1/ACT_D1a_MO/NNZ"
#define H5D_SP_SYM_ACT_D1A_MO_VAL "/SP_SYM_D1/ACT_D1a_MO/VAL"
#define H5D_SP_SYM_ACT_D1A_MO_ROW_IDX "/SP_SYM_D1/ACT_D1a_MO/ROW_IDX"
#define H5D_SP_SYM_ACT_D1A_MO_COL_IDX "/SP_SYM_D1/ACT_D1a_MO/COL_IDX"

#define H5D_SP_SYM_ACT_D1B_MO_NNZ "/SP_SYM_D1/ACT_D1b_MO/NNZ"
#define H5D_SP_SYM_ACT_D1B_MO_VAL "/SP_SYM_D1/ACT_D1b_MO/VAL"
#define H5D_SP_SYM_ACT_D1B_MO_ROW_IDX "/SP_SYM_D1/ACT_D1b_MO/ROW_IDX"
#define H5D_SP_SYM_ACT_D1B_MO_COL_IDX "/SP_SYM_D1/ACT_D1b_MO/COL_IDX"

/* if self.ref_method == 'MCSCF': */
#define H5D_FULL_D2AA_MO "/D/D2/FULL_D2AA_MO"
#define H5D_FULL_D2AB_MO "/D/D2/FULL_D2AB_MO"
#define H5D_FULL_D2BB_MO "/D/D2/FULL_D2BB_MO"

#define H5D_ACT_D2AA_MO "/D/D2/ACT_D2AA_MO"
#define H5D_ACT_D2AB_MO "/D/D2/ACT_D2AB_MO"
#define H5D_ACT_D2BB_MO "/D/D2/ACT_D2BB_MO"

#define H5D_FULL_D2_MO "/D/D2/FULL_D2_MO"
#define H5D_ACT_D2_MO "/D/D2/ACT_D2_MO"

#define H5D_SP_SYM_FULL_D2AB_MO_NNZ "/SP_SYM_D2/FULL_D2ab_MO/NNZ"
#define H5D_SP_SYM_FULL_D2AB_MO_VAL "/SP_SYM_D2/FULL_D2ab_MO/VAL"
#define H5D_SP_SYM_FULL_D2AB_MO_DIM1_IDX "/SP_SYM_D2/FULL_D2ab_MO/DIM1_IDX"
#define H5D_SP_SYM_FULL_D2AB_MO_DIM2_IDX "/SP_SYM_D2/FULL_D2ab_MO/DIM2_IDX"
#define H5D_SP_SYM_FULL_D2AB_MO_DIM3_IDX "/SP_SYM_D2/FULL_D2ab_MO/DIM3_IDX"
#define H5D_SP_SYM_FULL_D2AB_MO_DIM4_IDX "/SP_SYM_D2/FULL_D2ab_MO/DIM4_IDX"

#define H5D_SP_SYM_ACT_D2AB_MO_NNZ "/SP_SYM_D2/ACT_D2ab_MO/NNZ"
#define H5D_SP_SYM_ACT_D2AB_MO_VAL "/SP_SYM_D2/ACT_D2ab_MO/VAL"
#define H5D_SP_SYM_ACT_D2AB_MO_DIM1_IDX "/SP_SYM_D2/ACT_D2ab_MO/DIM1_IDX"
#define H5D_SP_SYM_ACT_D2AB_MO_DIM2_IDX "/SP_SYM_D2/ACT_D2ab_MO/DIM2_IDX"
#define H5D_SP_SYM_ACT_D2AB_MO_DIM3_IDX "/SP_SYM_D2/ACT_D2ab_MO/DIM3_IDX"
#define H5D_SP_SYM_ACT_D2AB_MO_DIM4_IDX "/SP_SYM_D2/ACT_D2ab_MO/DIM4_IDX"
       
#define H5D_W "/GRIDS/W"
#define H5D_X "/GRIDS/X"
#define H5D_Y "/GRIDS/Y"
#define H5D_Z "/GRIDS/Z"

#define H5D_PHI_AO "/PHI/PHI_AO"  
#define H5D_PHI_AO_X "/PHI/PHI_AO_X"
#define H5D_PHI_AO_Y "/PHI/PHI_AO_Y" 
#define H5D_PHI_AO_Z "/PHI/PHI_AO_Z" 

#define H5D_PHI_MO "/PHI/PHI_MO"  
#define H5D_PHI_MO_X "/PHI/PHI_MO_X" 
#define H5D_PHI_MO_Y "/PHI/PHI_MO_Y" 
#define H5D_PHI_MO_Z "/PHI/PHI_MO_Z" 

#endif // TOC_H
